#!/usr/bin/env bash

# Reference genome details
REFERENCE_NAME="hg38"
REFERENCE_GENOME="${REFERENCE_DIR}/${REFERENCE_NAME}.fa"
REFERENCE_DICT="${REFERENCE_GENOME%.fa}.dict"
REFERENCE_INDEX="${REFERENCE_GENOME}.fai"

# Known sites for BQSR
KNOWN_SITES_VCF="${REFERENCE_DIR}/dbsnp.vcf"
KNOWN_SITES_VCF_IDX="${KNOWN_SITES_VCF}.idx"

# Read Group information
RG_ID="$SAMPLE_NAME"
RG_SM="$SAMPLE_NAME"
RG_PL="ILLUMINA"
RG_STRING="@RG\tID:$RG_ID\tSM:$RG_SM\tPL:$RG_PL"

# Funcotator configuration
FUNCOTATOR_REF_VERSION="hg38"
FUNCOTATOR_DATA_SOURCES="${FUNCOTATOR_DATA_SOURCES_DIR}"
FUNCOTATOR_OUTPUT_FORMAT="VCF"
